// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class SU25LeopardDBContext : DbContext
{
    public SU25LeopardDBContext()
    {
    }

    public SU25LeopardDBContext(DbContextOptions<SU25LeopardDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<LeopardAccount> LeopardAccounts { get; set; }

    public virtual DbSet<LeopardProfile> LeopardProfiles { get; set; }

    public virtual DbSet<LeopardType> LeopardTypes { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer(GetConnectionString());

    private string? GetConnectionString()
    {
        IConfiguration config = new ConfigurationBuilder()
             .SetBasePath(Directory.GetCurrentDirectory())
                    .AddJsonFile("appsettings.json", true, true)
                    .Build();
        var strConn = config.GetConnectionString("DBConnection");

        return strConn;
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<LeopardAccount>(entity =>
        {
            entity.HasKey(e => e.AccountId);

            entity.ToTable("LeopardAccount");

            entity.Property(e => e.AccountId).HasColumnName("AccountID");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Password).HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<LeopardProfile>(entity =>
        {
            entity.ToTable("LeopardProfile");

            entity.Property(e => e.CareNeeds)
                .IsRequired()
                .HasMaxLength(1500);
            entity.Property(e => e.Characteristics)
                .IsRequired()
                .HasMaxLength(2000);
            entity.Property(e => e.LeopardName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.HasOne(d => d.LeopardType).WithMany(p => p.LeopardProfiles)
                .HasForeignKey(d => d.LeopardTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LeopardProfile_LeopardType");
        });

        modelBuilder.Entity<LeopardType>(entity =>
        {
            entity.ToTable("LeopardType");

            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.LeopardTypeName).HasMaxLength(250);
            entity.Property(e => e.Origin).HasMaxLength(250);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}