// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PRN232_SU25_SE184673.Repository.Models;

public partial class LeopardProfile
{
    public int LeopardProfileId { get; set; }

    public int LeopardTypeId { get; set; }

    [RegularExpression("^([A-Z0-9][a-zA-Z0-9#]*\\s)*([A-Z0-9][a-zA-Z0-9#]*)$", ErrorMessage = "Name is not valid")]
    public string LeopardName { get; set; }

    [Range(15, int.MaxValue, ErrorMessage ="Weight must above 15")]
    public double Weight { get; set; }

    public string Characteristics { get; set; }

    public string CareNeeds { get; set; }

    public DateTime ModifiedDate { get; set; }

    public virtual LeopardType LeopardType { get; set; }
}