// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Repository.Models;

public partial class LeopardType
{
    public int LeopardTypeId { get; set; }

    public string LeopardTypeName { get; set; }

    public string Origin { get; set; }

    public string Description { get; set; }
    [JsonIgnore]
    public virtual ICollection<LeopardProfile> LeopardProfiles { get; set; } = new List<LeopardProfile>();
}