// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DAO.Models;

public partial class LeopardProfile
{
    public int LeopardProfileId { get; set; }

    public int LeopardTypeId { get; set; }

    [Required]
    [RegularExpression(@"^([A-Z0-9][a-zA-Z0-9#]*\s)*([A-Z0-9][a-zA-Z0-9#]*)$",
            ErrorMessage = "ModelName must start with a capital or digit and contain only letters, digits, or '#' with spaces between valid parts.")]
    public string LeopardName { get; set; }

    [Required]
    [Range(0.01, double.MaxValue, ErrorMessage = "Price must be greater than 0.")]
    public double Weight { get; set; }

    public string Characteristics { get; set; }

    public string CareNeeds { get; set; }

    public DateTime ModifiedDate { get; set; }

    public virtual LeopardType LeopardType { get; set; }
}