// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232_SU25_SE184673.Repository.Models;

public partial class LeopardType
{
    public int LeopardTypeId { get; set; }

    public string LeopardTypeName { get; set; }

    public string Origin { get; set; }

    public string Description { get; set; }

    public virtual ICollection<LeopardProfile> LeopardProfiles { get; set; } = new List<LeopardProfile>();
}